[package]
name = "rustos"
version = "0.0.1"
authors = [ "you@example.com" ]

[lib]
name = "rustos"
crate-type = [ "staticlib" ]


[dependencies.core]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"

[dependencies.alloc]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"
default-features = false
features = [ "external_crate" ]

[dependencies.collections]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust.git"


[dependencies.bitflags]
path = "bitflags"

[dependencies.external]
path = "bump-pointer"

[dependencies.lazy-static-spin]
git = "https://github.com/RustOS-Fork-Holding-Ground/lazy-static-spin"

[dependencies.spinlock]
git = "https://github.com/RustOS-Fork-Holding-Ground/spinlock-rs"

[dependencies.rlibc]
rlibc = "https://github.com/RustOS-Fork-Holding-Ground/rlibc"
