[package]
name = "rustos"
version = "0.0.1"
authors = [ "you@example.com" ]

[lib]
name = "rustos"
crate-type = [ "staticlib" ]


[dependencies.core]
path = "lib/rust/cargo/core"

[dependencies.alloc]
path = "lib/rust/cargo/alloc"
default-features = false
features = [ "external_crate" ]

[dependencies.collections]
path = "lib/rust/cargo/collections"

[dependencies.external]
path = "bump-pointer"

[dependencies.lazy_static]
path = "lib/lazy-static.rs"

[dependencies.spin]
path = "lib/spinlock-rs"
features = [ "no_std" ]

[dependencies.rlibc]
path = "lib/rlibc"
