[package]
name = "rustos"
version = "0.0.1"
authors = [ "you@example.com" ]

[lib]
name = "rustos"
crate-type = [ "staticlib" ]


[dependencies.core]
git = "https://github.com/ryanra/rust.git"
branch = "rustos-nightly"

[dependencies.alloc]
git = "https://github.com/ryanra/rust.git"
branch = "rustos-nightly"
default-features = false
features = [ "external_crate" ]

[dependencies.collections]
git = "https://github.com/ryanra/rust.git"
branch = "rustos-nightly"

[dependencies.external]
path = "bump-pointer"

[dependencies.lazy_static_spin]
git = "https://github.com/RustOS-Fork-Holding-Ground/lazy-static-spin"
branch = "spin"

[dependencies.spin]
git = "https://github.com/ryanra/spinlock-rs"
features = [ "no_std" ]

[dependencies.rlibc]
git = "https://github.com/ryanra/rlibc"
