[package]

# name is mandated by liballoc for nowx

name = "external"
version = "0.0.1"
authors = [ "you@example.com" ]
features = [ "no_std" ]

[lib]
name = "external"

[dependencies.core]
path = "../lib/rust/cargo/core"

